### ISSUE TITLE
[Instant Apps] 不具合修正

### ISSUE THREAD

**Issue by mag0716** [mag0716/Android_P#66]
## 概要

#64 で試したが以下のエラーで想定通りの動作をしない。

```
2019-02-26 21:24:07.591 1274-6381/? I/ActivityManager: START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=https://mag0716.github.io/... flg=0x10000000 cmp=com.android.vending/com.google.android.finsky.instantapps.EphemeralInstallerActivity (has extras)} from uid 10053
    
    --------- beginning of main
2019-02-26 21:24:07.601 839-839/? D/android.hardware.power@1.3-service.crosshatch-libperfmgr: LAUNCH ON
2019-02-26 21:24:07.606 28054-28054/? I/AppLifecycleTracker: onActivityPaused: 
2019-02-26 21:24:07.607 1274-9540/? E/ActivityManager: applyOptionsLocked: Unknown animationType=0
2019-02-26 21:24:07.608 2523-2523/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@5fb0ab8
2019-02-26 21:24:07.621 2523-2523/? I/Finsky:instant_app_inst: [2] com.google.android.finsky.instantapps.EphemeralInstallerActivity.b(163): Handling install intent for token 908aaff5-1883-4c79-8e12-01b60947d1df packageName: com.github.mag0716.appbundlessample
2019-02-26 21:24:07.623 2523-2543/? I/Finsky:instant_app_inst: [12920] com.google.android.finsky.instantappsbackendclient.impl.x.a(62): GetAppSplits no cache entry
2019-02-26 21:24:07.642 2523-2523/? D/PhenotypeUpdateService: onCreate called
2019-02-26 21:24:07.660 2523-2819/? D/PhenotypeUpdateService: Registering with Phenotype
2019-02-26 21:24:07.684 1274-1301/? I/ActivityManager: Displayed com.android.vending/com.google.android.finsky.instantapps.EphemeralInstallerActivity: +91ms
2019-02-26 21:24:07.704 839-839/? D/android.hardware.power@1.3-service.crosshatch-libperfmgr: LAUNCH OFF
2019-02-26 21:24:07.846 2523-2543/? E/Finsky:instant_app_inst: [12920] com.google.android.finsky.instantapps.e.ag.c(143): Failed to hit backend for GetAppSplits. Reason=HTTP(500) Response was unsuccessful
    com.google.android.finsky.instantappsbackendclient.InstantAppsClient$InstantAppsClientException: HTTP(500) Response was unsuccessful
        at com.google.android.finsky.instantappsbackendclient.impl.x.a(SourceFile:307)
        at com.google.android.finsky.instantappsbackendclient.impl.x.a(SourceFile:48)
        at com.google.android.finsky.instantapps.e.ag.c(SourceFile:46)
        at com.google.android.finsky.instantapps.e.ag.call(SourceFile:212)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.instantapps.common.gms.au.run(SourceFile:3)
        at java.lang.Thread.run(Thread.java:764)
2019-02-26 21:24:07.847 2523-2563/? E/Isotope: UID: [10053]  PID: [2523] LaunchTask : Could not get launch status
    java.util.concurrent.ExecutionException: com.google.android.finsky.instantappsbackendclient.InstantAppsClient$InstantAppsClientException: HTTP(500) Response was unsuccessful
        at java.util.concurrent.FutureTask.report(FutureTask.java:123)
        at java.util.concurrent.FutureTask.get(FutureTask.java:193)
        at com.google.android.finsky.instantapps.e.ag.b(SourceFile:24)
        at com.google.android.finsky.instantapps.e.r.a(SourceFile:151)
        at com.google.android.finsky.instantapps.e.t.a(Unknown Source:16)
        at com.google.android.instantapps.common.gms.s.run(Unknown Source:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at com.google.android.instantapps.common.gms.au.run(SourceFile:3)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: com.google.android.finsky.instantappsbackendclient.InstantAppsClient$InstantAppsClientException: HTTP(500) Response was unsuccessful
        at com.google.android.finsky.instantappsbackendclient.impl.x.a(SourceFile:307)
        at com.google.android.finsky.instantappsbackendclient.impl.x.a(SourceFile:48)
        at com.google.android.finsky.instantapps.e.ag.c(SourceFile:46)
        at com.google.android.finsky.instantapps.e.ag.call(SourceFile:212)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at com.google.android.instantapps.common.gms.au.run(SourceFile:3) 
        at java.lang.Thread.run(Thread.java:764) 
2019-02-26 21:24:07.850 2523-2584/? I/PlayCommon: [12951] com.google.android.play.b.g.d(132): Preparing logs for uploading
2019-02-26 21:24:07.854 2523-2584/? I/PlayCommon: [12951] com.google.android.play.b.g.a(325): Connecting to server: https://play.googleapis.com/play/log?format=raw&proto_v2=true
2019-02-26 21:24:07.890 28054-28054/? I/AppLifecycleTracker: onActivityResumed: 
2019-02-26 21:24:07.965 2523-2584/? I/PlayCommon: [12951] com.google.android.play.b.g.a(416): Successfully uploaded logs.
2019-02-26 21:24:07.995 840-901/? I/CHRE: @ 1174020.125: [AR_CHRE] still: 100
```

## TODO

* [サンプル](https://github.com/googlesamples/android-dynamic-features) を internal test track にリリースしてみる
* Issue Track 確認

## 参考

* https://developer.android.com/topic/google-play-instant/getting-started/instant-enabled-app-bundle
* http://t-miliya612.hatenablog.com/entry/2018/04/19/003804

**Comment by mag0716** [comment]
https://android-developers.googleblog.com/2019/03/the-latest-android-app-bundle-updates.html?linkId=65112207

で何か変わった？
